["id"=>"2781","Country"=>"United States Dollar ($)","Currency"=>"USD"],
					["id"=>"3526","Country"=>"Albanian Lek (L)","Currency"=>"ALL"],
					["id"=>"3537","Country"=>"Algerian Dinar (د.ج)","Currency"=>"DZD"],
					["id"=>"2821","Country"=>"Argentine Peso ($)","Currency"=>"ARS"],
					["id"=>"3527","Country"=>"Armenian Dram (֏)","Currency"=>"AMD"],
					["id"=>"2782","Country"=>"Australian Dollar ($)","Currency"=>"AUD"],
					["id"=>"3528","Country"=>"Azerbaijani Manat (₼)","Currency"=>"AZN"],
					["id"=>"3531","Country"=>"Bahraini Dinar (.د.ب)","Currency"=>"BHD"],
					["id"=>"3530","Country"=>"Bangladeshi Taka (৳)","Currency"=>"BDT"],
					["id"=>"3533","Country"=>"Belarusian Ruble (Br)","Currency"=>"BYN"],
					["id"=>"3532","Country"=>"Bermudan Dollar ($)","Currency"=>"BMD"],
					["id"=>"2832","Country"=>"Bolivian Boliviano (Bs.)","Currency"=>"BOB"],
					["id"=>"3529","Country"=>"Bosnia-Herzegovina Convertible Mark (KM)","Currency"=>"BAM"],
					["id"=>"2783","Country"=>"Brazilian Real (R$)","Currency"=>"BRL"],
					["id"=>"2814","Country"=>"Bulgarian Lev (лв)","Currency"=>"BGN"],
					["id"=>"3549","Country"=>"Cambodian Riel (៛)","Currency"=>"KHR"],
					["id"=>"2784","Country"=>"Canadian Dollar ($)","Currency"=>"CAD"],
					["id"=>"2786","Country"=>"Chilean Peso ($)","Currency"=>"CLP"],
					["id"=>"2787","Country"=>"Chinese Yuan (¥)","Currency"=>"CNY"],
					["id"=>"2820","Country"=>"Colombian Peso ($)","Currency"=>"COP"],
					["id"=>"3534","Country"=>"Costa Rican Colón (₡)","Currency"=>"CRC"],
					["id"=>"2815","Country"=>"Croatian Kuna (kn)","Currency"=>"HRK"],
					["id"=>"3535","Country"=>"Cuban Peso ($)","Currency"=>"CUP"],
					["id"=>"2788","Country"=>"Czech Koruna (Kč)","Currency"=>"CZK"],
					["id"=>"2789","Country"=>"Danish Krone (kr)","Currency"=>"DKK"],
					["id"=>"3536","Country"=>"Dominican Peso ($)","Currency"=>"DOP"],
					["id"=>"3538","Country"=>"Egyptian Pound (£)","Currency"=>"EGP"],
					["id"=>"2790","Country"=>"Euro (€)","Currency"=>"EUR"],
					["id"=>"3539","Country"=>"Georgian Lari (₾)","Currency"=>"GEL"],
					["id"=>"3540","Country"=>"Ghanaian Cedi (₵)","Currency"=>"GHS"],
					["id"=>"3541","Country"=>"Guatemalan Quetzal (Q)","Currency"=>"GTQ"],
					["id"=>"3542","Country"=>"Honduran Lempira (L)","Currency"=>"HNL"],
					["id"=>"2792","Country"=>"Hong Kong Dollar ($)","Currency"=>"HKD"],
					["id"=>"2793","Country"=>"Hungarian Forint (Ft)","Currency"=>"HUF"],
					["id"=>"2818","Country"=>"Icelandic Króna (kr)","Currency"=>"ISK"],
					["id"=>"2796","Country"=>"Indian Rupee (₹)","Currency"=>"INR"],
					["id"=>"2794","Country"=>"Indonesian Rupiah (Rp)","Currency"=>"IDR"],
					["id"=>"3544","Country"=>"Iranian Rial (﷼)","Currency"=>"IRR"],
					["id"=>"3543","Country"=>"Iraqi Dinar (ع.د)","Currency"=>"IQD"],
					["id"=>"2795","Country"=>"Israeli New Shekel (₪)","Currency"=>"ILS"],
					["id"=>"3545","Country"=>"Jamaican Dollar ($)","Currency"=>"JMD"],
					["id"=>"2797","Country"=>"Japanese Yen (¥)","Currency"=>"JPY"],
					["id"=>"3546","Country"=>"Jordanian Dinar (د.ا)","Currency"=>"JOD"],
					["id"=>"3551","Country"=>"Kazakhstani Tenge (₸)","Currency"=>"KZT"],
					["id"=>"3547","Country"=>"Kenyan Shilling (Sh)","Currency"=>"KES"],
					["id"=>"3550","Country"=>"Kuwaiti Dinar (د.ك)","Currency"=>"KWD"],
					["id"=>"3548","Country"=>"Kyrgystani Som (с)","Currency"=>"KGS"],
					["id"=>"3552","Country"=>"Lebanese Pound (ل.ل)","Currency"=>"LBP"],
					["id"=>"3556","Country"=>"Macedonian Denar (ден)","Currency"=>"MKD"],
					["id"=>"2800","Country"=>"Malaysian Ringgit (RM)","Currency"=>"MYR"],
					["id"=>"2816","Country"=>"Mauritian Rupee (₨)","Currency"=>"MUR"],
					["id"=>"2799","Country"=>"Mexican Peso ($)","Currency"=>"MXN"],
					["id"=>"3555","Country"=>"Moldovan Leu (L)","Currency"=>"MDL"],
					["id"=>"3558","Country"=>"Mongolian Tugrik (₮)","Currency"=>"MNT"],
					["id"=>"3554","Country"=>"Moroccan Dirham (د.م.)","Currency"=>"MAD"],
					["id"=>"3557","Country"=>"Myanma Kyat (Ks)","Currency"=>"MMK"],
					["id"=>"3559","Country"=>"Namibian Dollar ($)","Currency"=>"NAD"],
					["id"=>"3561","Country"=>"Nepalese Rupee (₨)","Currency"=>"NPR"],
					["id"=>"2811","Country"=>"New Taiwan Dollar ($)","Currency"=>"TWD"],
					["id"=>"2802","Country"=>"New Zealand Dollar ($)","Currency"=>"NZD"],
					["id"=>"3560","Country"=>"Nicaraguan Córdoba (C$)","Currency"=>"NIO"],
					["id"=>"2819","Country"=>"Nigerian Naira (₦)","Currency"=>"NGN"],
					["id"=>"2801","Country"=>"Norwegian Krone (kr)","Currency"=>"NOK"],
					["id"=>"3562","Country"=>"Omani Rial (ر.ع.)","Currency"=>"OMR"],
					["id"=>"2804","Country"=>"Pakistani Rupee (₨)","Currency"=>"PKR"],
					["id"=>"3563","Country"=>"Panamanian Balboa (B/.)","Currency"=>"PAB"],
					["id"=>"2822","Country"=>"Peruvian Sol (S/.)","Currency"=>"PEN"],
					["id"=>"2803","Country"=>"Philippine Peso (₱)","Currency"=>"PHP"],
					["id"=>"2805","Country"=>"Polish Złoty (zł)","Currency"=>"PLN"],
					["id"=>"2791","Country"=>"Pound Sterling (£)","Currency"=>"GBP"],
					["id"=>"3564","Country"=>"Qatari Rial (ر.ق)","Currency"=>"QAR"],
					["id"=>"2817","Country"=>"Romanian Leu (lei)","Currency"=>"RON"],
					["id"=>"2806","Country"=>"Russian Ruble (₽)","Currency"=>"RUB"],
					["id"=>"3566","Country"=>"Saudi Riyal (ر.س)","Currency"=>"SAR"],
					["id"=>"3565","Country"=>"Serbian Dinar (дин.)","Currency"=>"RSD"],
					["id"=>"2808","Country"=>"Singapore Dollar ($)","Currency"=>"SGD"],
					["id"=>"2812","Country"=>"South African Rand (Rs)","Currency"=>"ZAR"],
					["id"=>"2798","Country"=>"South Korean Won (₩)","Currency"=>"KRW"],
					["id"=>"3567","Country"=>"South Sudanese Pound (£)","Currency"=>"SSP"],
					["id"=>"3573","Country"=>"Sovereign Bolivar (Bs.)","Currency"=>"VES"],
					["id"=>"3553","Country"=>"Sri Lankan Rupee (Rs)","Currency"=>"LKR"],
					["id"=>"2807","Country"=>"Swedish Krona ( kr)","Currency"=>"SEK"],
					["id"=>"2785","Country"=>"Swiss Franc (Fr)","Currency"=>"CHF"],
					["id"=>"2809","Country"=>"Thai Baht (฿)","Currency"=>"THB"],
					["id"=>"3569","Country"=>"Trinidad and Tobago Dollar ($)","Currency"=>"TTD"],
					["id"=>"3568","Country"=>"Tunisian Dinar (د.ت)","Currency"=>"TND"],
					["id"=>"2810","Country"=>"Turkish Lira (₺)","Currency"=>"TRY"],
					["id"=>"3570","Country"=>"Ugandan Shilling (Sh)","Currency"=>"UGX"],
					["id"=>"2824","Country"=>"Ukrainian Hryvnia (₴)","Currency"=>"UAH"],
					["id"=>"2813","Country"=>"United Arab Emirates Dirham (د.إ)","Currency"=>"AED"],
					["id"=>"3571","Country"=>"Uruguayan Peso ($)","Currency"=>"UYU"],
					["id"=>"3572","Country"=>"Uzbekistan Som (so'm)","Currency"=>"UZS"],
					["id"=>"2823","Country"=>"Vietnamese Dong (₫)","Currency"=>"VND"]